version: 1.2
notebooks:
  - format: JUPYTER
    path: /LORIS/preprocessing_data.ipynb
    topic: LORIS raw data preprocessing from Chang et al. 2024 article.
    authors:
      - name: Paulo Lyra-Jr
        email: paulocilas.moraislyra@moffitt.org
        name: Jeremy Goecks
        email: jeremy.goecks@moffitt.org
workflows:
  - subclass: GALAXY 
    primaryDescriptorPath: /LORIS/galaxy_workflow/Galaxy-ML2-LORIS_model.ga
    topic: LORIS model (Chang et al., 2024) Reproducibility using Galaxy-ML tools
    authors:
      - name: Paulo Lyra-Jr
        email: paulocilas.moraislyra@moffitt.org
        name: Jeremy Goecks
        email: jeremy.goecks@moffitt.org
